on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: xdebug, soap
        coverage: xdebug

    - name: vvv
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache dependencies installed with composer
      uses: actions/cache@v1.0.2
      with:
        path: ~/.composer/cache
        key: php8.1-composer-locked-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php8.1-composer-locked-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: CI
      run: composer ci

    - name: PHPStan
      run: composer phpstan

    - name: Run tests
      run: composer coverage
