on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: vvv
      run: php -v

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache dependencies installed with composer
      uses: actions/cache@v1.0.2
      with:
        path: ~/.composer/cache
        key: php7.3-composer-locked-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php7.3-composer-locked-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: CI
      run: composer ci

    - name: PHPStan
      run: composer phpstan

    - name: Run tests
      run: composer coverage
